name: Static Website Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Validate HTML
      uses: actions/github-script@v6
      with:
        script: |
          // 简单检查test.html是否存在
          const fs = require('fs');
          if (!fs.existsSync('test.html')) {
            core.setFailed('test.html not found');
          }
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: static-website
        path: |
          test.html
          asset/
          opencv.js
        retention-days: 1
        
    # 如果需要部署到GitHub Pages，取消以下注释
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./
    #     keep_files: false
